spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  client:
    register-with-eureka: false
    fetch-registry: false
    initial-instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/
