spring:
  application:
    name: service-gateway
server:
  port: 8672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: auth-service
    service-hi:
      path: /service-hi/**
      serviceId: service-hi
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000